notifications:
  slack: wsi-t113:SRHSOd3CgFDUwFxqv8SCXuIf
  email: false

sudo: false

language: ruby

services:
 - docker

script:
 - echo 'Build and check docker image'
 - docker build -t template-toolkit .
 - docker images | grep -c template-toolkit
 - echo 'Verify program(s) from this repo'
 - docker run -t --rm template-toolkit tpage -h
